name: Setup

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Setup Cache
      uses: actions/cache@v3
      id: cache
      with:
        path: '**/node_modules'
        key: npm-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm ci
      shell: bash
